region_map = {
    "Gen.G": "LCK",
    "Beijing JDG Intel Esports Club": "LPL",
    "Suzhou LNG Esports": "LPL",
    "G2 Esports": "LEC",
    "Cloud9": "LCS",
    "T1": "LCK",
    "Dplus Kia": "LCK",
    "Golden Guardians": "LCS",
    "NRG": "LCS",
    "SHANGHAI EDWARD GAMING HYCAN": "LPL",
    "WeiboGaming FAW AUDI": "LPL",
    "Team BDS": "LEC",
    "TOP ESPORTS": "LPL",
    "FlyQuest": "LCS",
    "MAD Lions": "LEC",
    "Royal Never Give Up": "LPL",
    "Bilibili Gaming Pingan Bank": "LPL",
    "NoTeamFound": "LOL",
    "Team Liquid Honda": "LCS", 
    "CLG": "LCS",
    "KOI": "LEC",
    "Astralis": "LEC",
    "Hanwha Life Esports": "LCK",
    "FunPlus Phoenix": "LPL",
    "Team Vitality": "LEC",
    "Fnatic": "LEC",
    "SK Gaming": "LEC",
    "TSM": "LCS",
    "100 Thieves": "LCS",
    "Invictus Gaming": "LPL",
    "Dignitas": "LCS",
    "EXCEL": "LEC",
    "OKSavingsBank BRION": "LCK",
    "Immortals Progressive": "LCS",
    "Liiv SANDBOX": "LCK",
    "Team Heretics": "LEC",
    "NongShim REDFORCE": "LCK",
    "LGD GAMING": "LPL",
    "DRX": "LCK",
    "Oh My God": "LPL",
    "Evil Geniuses LG": "LCS",
    "Kwangdong Freecs": "LCK",
    "kt Rolster" : "LCK",
    "Ninjas in Pyjamas" : "LPL",
    "Anyones Legend" : "LPL",
    "Rare Atom" : "LPL",
    "Team WE" : "LPL",
    "ThunderTalk Gaming" : "LPL",
    "Ultra Prime" : "LPL",
    "Movistar R7" : "LLA",
    "GAM Esports" : "VCS",
    "LOUD" : "CBLOL",
    "PSG Talon" : "PCS",
    "DetonatioN FocusMe" : "LJL"
}